name: Deploy to Smithery.ai

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Deploy to Smithery.ai
        run: ./scripts/deploy.sh
        env:
          SMITHERY_API_KEY: ${{ secrets.SMITHERY_API_KEY }}
          SMITHERY_PROJECT_ID: ${{ secrets.SMITHERY_PROJECT_ID }}
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }} 